groups:
- name: pigeon.go_process.rules
  rules:
  - alert: Pigeon-HighMemoryUsage
    expr: sum by (kubernetes_pod_name)(rate(process_resident_memory_bytes{kubernetes_pod_name=~"^pigeon.*"}[5m])) > 200000000
    for: 5m
    labels:
      severity: critical
      domain: ride
    annotations:
      summary: "High memory usage"
      description: "Service consumes high memory (average > 200MiB) for the last minute."
