version: "3.3"

services:

  pigeon:
    image: pigeon
    build: .
    container_name: pigeon_dev
    restart: on-failure
    ports:
      - "50000:50000"

  pigeon_ci:
    image: pigeon_ci
    container_name: pigeon_ci
    build:
      context: ./../../../
      dockerfile: infra/build/Dockerfile.ci