// +build !test

// Code generated by counterfeiter. DO NOT EDIT.
package twiliofakes

import (
	"sync"

	"github.com/taxibeat/pigeon/twilio"
)

type FakeProgrammableSMS struct {
	SendStub        func(twilio.MessageCreate) (twilio.MessageResource, error)
	sendMutex       sync.RWMutex
	sendArgsForCall []struct {
		arg1 twilio.MessageCreate
	}
	sendReturns struct {
		result1 twilio.MessageResource
		result2 error
	}
	sendReturnsOnCall map[int]struct {
		result1 twilio.MessageResource
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProgrammableSMS) Send(arg1 twilio.MessageCreate) (twilio.MessageResource, error) {
	fake.sendMutex.Lock()
	ret, specificReturn := fake.sendReturnsOnCall[len(fake.sendArgsForCall)]
	fake.sendArgsForCall = append(fake.sendArgsForCall, struct {
		arg1 twilio.MessageCreate
	}{arg1})
	fake.recordInvocation("Send", []interface{}{arg1})
	fake.sendMutex.Unlock()
	if fake.SendStub != nil {
		return fake.SendStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.sendReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProgrammableSMS) SendCallCount() int {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	return len(fake.sendArgsForCall)
}

func (fake *FakeProgrammableSMS) SendCalls(stub func(twilio.MessageCreate) (twilio.MessageResource, error)) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = stub
}

func (fake *FakeProgrammableSMS) SendArgsForCall(i int) twilio.MessageCreate {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	argsForCall := fake.sendArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProgrammableSMS) SendReturns(result1 twilio.MessageResource, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	fake.sendReturns = struct {
		result1 twilio.MessageResource
		result2 error
	}{result1, result2}
}

func (fake *FakeProgrammableSMS) SendReturnsOnCall(i int, result1 twilio.MessageResource, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	if fake.sendReturnsOnCall == nil {
		fake.sendReturnsOnCall = make(map[int]struct {
			result1 twilio.MessageResource
			result2 error
		})
	}
	fake.sendReturnsOnCall[i] = struct {
		result1 twilio.MessageResource
		result2 error
	}{result1, result2}
}

func (fake *FakeProgrammableSMS) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProgrammableSMS) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ twilio.ProgrammableSMS = new(FakeProgrammableSMS)
