{
 "title": "Pigeon Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Goroutines Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_name=\"pigeon\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages  handled by twilio provider",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pigeon_messaging_http_requests{status_code=\"201\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(pigeon_messaging_http_requests{status_code=\"201\"}[5m])) by (url, method)",
     "legendFormat": "{{url}}-{{method}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{container_name=\"pigeon\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Twilio 95th percentile latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le) (rate(pigeon_messaging_latency_seconds_bucket{status_code=\"201\"}[5m])))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.95, sum  by (le, url, method) (rate(pigeon_messaging_latency_seconds_bucket{status_code=\"201\"}[5m])))",
     "legendFormat": "{{url}}-{{method}}"
    }
   ]
  }
 ]
}