{
 "title": "Pigeon Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(thanos_build_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Message rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pigeon_messenger_handled_messages{success=\"true\", time_critical=\"true\"}[5m])) by (type, provider)",
     "legendFormat": "critical-{{provider}}-{{type}}"
    },
    {
     "expr": "sum(rate(pigeon_messenger_handled_messages{success=\"true\", time_critical=\"false\"}[5m])) by (type, provider)",
     "legendFormat": "non_critical-{{provider}}-{{type}}"
    }
   ]
  },
  {
   "title": "HTTP Message rate per provider",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pigeon_messaging_http_requests{status_code=~\"2[0-9]{2}\"}[5m])) by (provider)",
     "legendFormat": "total-{{provider}}"
    },
    {
     "expr": "sum(rate(pigeon_messaging_http_requests{status_code=~\"2[0-9]{2}\"}[5m])) by (url, method, provider)",
     "legendFormat": "{{method}}-{{provider}}-{{url}}"
    }
   ]
  },
  {
   "title": "Message Error rate %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(pigeon_messenger_handled_messages{success!=\"true\"}[5m])) by (type, provider) / sum(rate(pigeon_messenger_handled_messages[5m])) by (type,provider)",
     "legendFormat": "total-{{provider}}-{{type}}"
    },
    {
     "expr": "100 * sum(rate(pigeon_messenger_handled_messages{success!=\"true\",time_critical=\"true\"}[5m])) by (type, provider) / sum(rate(pigeon_messenger_handled_messages{time_critical=\"true\"}[5m])) by (type,provider)",
     "legendFormat": "critical-{{provider}}-{{type}}"
    },
    {
     "expr": "100 * sum(rate(pigeon_messenger_handled_messages{success!=\"true\",time_critical=\"false\"}[5m])) by (type, provider) / sum(rate(pigeon_messenger_handled_messages{time_critical=\"false\"}[5m])) by (type,provider)",
     "legendFormat": "non_critical-{{provider}}-{{type}}"
    }
   ]
  },
  {
   "title": "HTTP Error rate by provider %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(pigeon_messaging_http_requests{status_code!~\"2[0-9]{2}\"}[5m])) by (provider) / sum(rate(pigeon_messaging_http_requests[5m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Message 95th percentile latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider, type) (rate(pigeon_messenger_latency_seconds_bucket{success=\"true\"}[5m])))",
     "legendFormat": "total-{{provider}}-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider, type) (rate(pigeon_messenger_latency_seconds_bucket{success=\"true\", time_critical=\"true\"}[5m])))",
     "legendFormat": "critical-{{provider}}-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider, type) (rate(pigeon_messenger_latency_seconds_bucket{success=\"true\", time_critical=\"false\"}[5m])))",
     "legendFormat": "non_critical-{{provider}}-{{type}}"
    }
   ]
  },
  {
   "title": "HTTP 95th percentile latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.95, sum  by (le, provider) (rate(pigeon_messaging_latency_seconds_bucket{status_code=~\"2[0-9]{2}\"}[5m])))",
     "legendFormat": "total-{{provider}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum  by (le, url, method, provider) (rate(pigeon_messaging_latency_seconds_bucket{status_code=~\"2[0-9]{2}\"}[5m])))",
     "legendFormat": "{{provider}}-{{method}}-{{url}}"
    }
   ]
  },
  {
   "title": "Goroutines Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_name=\"pigeon\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{container_name=\"pigeon\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "HTTP Error rate by provider",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pigeon_messaging_http_requests{status_code!~\"2[0-9]{2}\"}[5m])) by (provider, status_code)",
     "legendFormat": "{{provider}}-{{status_code}}"
    }
   ]
  }
 ]
}